Traceback (most recent call last):
  File "C:\postgraduater\AI PLC\LLM-project-V2-执行者+提问者\test.py", line 46, in <module>
    loss.backward()
  File "C:\anaconda3\envs\image_test\lib\site-packages\torch\_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "C:\anaconda3\envs\image_test\lib\site-packages\torch\autograd\__init__.py", line 347, in backward
    _engine_run_backward(
  File "C:\anaconda3\envs\image_test\lib\site-packages\torch\autograd\graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Found dtype Double but expected Float
Traceback (most recent call last):
  File "C:\postgraduater\AI PLC\LLM-project-V2-执行者+提问者\test.py", line 46, in <module>
    loss.backward()
  File "C:\anaconda3\envs\image_test\lib\site-packages\torch\_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "C:\anaconda3\envs\image_test\lib\site-packages\torch\autograd\__init__.py", line 347, in backward
    _engine_run_backward(
  File "C:\anaconda3\envs\image_test\lib\site-packages\torch\autograd\graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Found dtype Double but expected Float
